### ISSUE TITLE
clash国内ip  clash土耳其节点  clash出站模式

### ISSUE THREAD

**Issue by clashvpn19** [clashvpn19/clashvpn#5]
推荐榜单1、爱连VPN
邀请好友注册充值返利高达40-50%
永久官网注册登陆网址：（打不开请点击下面导航）https://www.iovevpn.com/
永久导航：（最新网址进导航页面查找）https://www.ailianvpn.com/
爱连VPN手机下载（支持安卓-Winodws-MAC-苹果ios）https://www.ivpn.im
相比直连机场更加推荐购买中转机场。中转机场机器便宜一般更加带宽大，公网主要问题是出口偶尔会绕路导致网络波动影响。专线主要是不过墙延迟低，网络波动小，专线机场日常使用体验会更丝滑更舒服。机场比的是钞能力，速度要看机场的总带宽大小。稳定要看机场的资源质量，主要是看机场主的上游的线路质量，解锁看的是机场主的落地/解锁商是否优秀。机场带宽大和稳定性最重要。

### Clash 国内 IP

**Clash 国内 IP** 指的是配置 Clash 以便处理来自中国大陆的 IP 地址的流量。这通常涉及到设置规则以确保中国大陆的 IP 地址流量不经过代理，或者使用特定的代理节点来处理这些流量。

#### **1. 配置国内 IP 规则**

要配置国内 IP 地址的规则，通常你需要在 Clash 的配置文件中使用规则匹配功能。以下是一个配置示例：

```yaml
rules:
  - GEOIP,CN,DIRECT
  - MATCH,Proxy-Group
```

- `GEOIP,CN,DIRECT`：表示所有中国大陆的 IP 地址（根据 GeoIP 数据库）直接连接，不经过代理。
- `MATCH,Proxy-Group`：所有其他流量将根据配置的代理组进行处理。

#### **2. 获取国内 IP 数据库**

- Clash 使用 GeoIP 数据库来识别国内 IP 地址。可以从官方数据库提供者或第三方提供的数据库中获取更新。
- 确保配置文件中的 `GeoIP` 数据库是最新的，以准确识别国内 IP 地址。

### Clash 土耳其节点

**Clash 土耳其节点** 是指你配置的代理节点位于土耳其的服务器。使用土耳其节点可以帮助你绕过地域限制，或者优化访问土耳其网站的速度。

#### **1. 配置土耳其节点**

要添加土耳其节点，你需要在 Clash 的配置文件中定义这个节点。以下是一个节点配置示例：

```yaml
proxies:
  - name: "Turkey-Proxy"
    type: vmess
    server: turkish-server.example.com
    port: 443
    uuid: 123e4567-e89b-12d3-a456-426614174000
    alterId: 64
    cipher: auto
```

- `name`：节点的名称，便于识别。
- `server`：土耳其服务器的域名或 IP 地址。
- `port`：服务器的端口号。
- `uuid`：用于身份验证的 UUID。
- `alterId`：VMess 协议中的参数。
- `cipher`：加密方式。

#### **2. 使用土耳其节点**

在配置文件中定义了土耳其节点后，可以在 `proxy-groups` 中选择它：

```yaml
proxy-groups:
  - name: "Proxy-Group"
    type: select
    proxies:
      - Turkey-Proxy
      - Other-Proxy
```

在 `rules` 中设置规则来使用这个节点：

```yaml
rules:
  - DOMAIN-SUFFIX,example.tr,Turkey-Proxy
  - MATCH,Proxy-Group
```

### Clash 出站模式

**Clash 出站模式** 是指 Clash 如何处理出站流量。出站模式决定了流量是直接连接，还是通过代理节点转发。Clash 主要有以下几种出站模式：

#### **1. 直连（Direct）**

- **说明**：所有流量直接访问目标服务器，不经过任何代理。
- **配置**：在 `rules` 中使用 `DIRECT`，例如：

  ```yaml
  rules:
    - DOMAIN-SUFFIX,example.com,DIRECT
    - MATCH,Proxy-Group
  ```

#### **2. 代理（Proxy）**

- **说明**：所有流量都通过配置的代理节点进行转发。
- **配置**：在 `rules` 中使用代理节点或代理组，如：

  ```yaml
  rules:
    - DOMAIN-SUFFIX,example.com,Proxy-Group
    - MATCH,Proxy-Group
  ```

#### **3. 分流（Rule-Based）**

- **说明**：根据不同的规则决定流量是走代理还是直连。
- **配置**：设置复杂的规则来分流不同类型的流量。例如：

  ```yaml
  rules:
    - DOMAIN-SUFFIX,example.com,Proxy1
    - DOMAIN-SUFFIX,example.net,DIRECT
    - MATCH,Proxy-Group
  ```

#### **4. 全局模式（Global）**

- **说明**：所有流量都经过代理，无论目标地址是什么。
- **配置**：通常通过在 `proxy-groups` 中设置全局模式的代理：

  ```yaml
  proxy-groups:
    - name: "Global-Proxy"
      type: select
      proxies:
        - Proxy1
        - Proxy2

  rules:
    - MATCH,Global-Proxy
  ```
